#
# --- NOTE CLASS ---
# INIT EACH NOTE OBJECT USING ATTRIBUTE LIST READ
# FROM EACH LINE OF EXCEL FILE WITH PANDAS DATA FRAME
#


class Note:
    def __init__(self, NOTE_DATA):  # n=3 LIST OF BELOW DATA OBJECTS

        self.NOTE_TYPE = NOTE_DATA[0]  # LIST OF 5 BOOL VALUES, TRUE FOR EACH NOTE IN OBJECT
        self.SUSTAIN_LENGTH = NOTE_DATA[1]  # LENGTH OF SUSTAIN IN PIXELS (CONVERTED FROM SEC)
        self.TIME_STAMP = NOTE_DATA[2]  # PRECISE TIME STAMP OF NOTE IN SONG (FLOAT - SEC TO FRAMES)

        # TO-DO FOR CONTROLLER SUPPORT - ADD HO/PO
        # self.is_HOPO = NOTE_DATA[1]  # TRUE IF HAMMER-ON/PULL-OFF (NO STRUM REQUIRED)

        self.Y_POS = -264  # 1000 px TO CENTER OF HIT AREA
        self.HIT = False
